/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as authRouteRouteImport } from './routes/(auth)/route';
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in';
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up';
import { Route as PricingIndexRouteImport } from './routes/pricing/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any);
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any);
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any);
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sign-in': typeof authSignInRoute;
  '/sign-up': typeof authSignUpRoute;
  '/pricing/': typeof PricingIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof authSignInRoute;
  '/sign-up': typeof authSignUpRoute;
  '/pricing': typeof PricingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/(auth)': typeof authRouteRouteWithChildren;
  '/(auth)/sign-in': typeof authSignInRoute;
  '/(auth)/sign-up': typeof authSignUpRoute;
  '/pricing/': typeof PricingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/pricing/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sign-in' | '/sign-up' | '/pricing';
  id: '__root__' | '/' | '/(auth)' | '/(auth)/sign-in' | '/(auth)/sign-up' | '/pricing/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  PricingIndexRoute: typeof PricingIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(auth)': {
      id: '/(auth)';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof authSignInRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof authSignUpRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    '/pricing/': {
      id: '/pricing/';
      path: '/pricing';
      fullPath: '/pricing/';
      preLoaderRoute: typeof PricingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute;
  authSignUpRoute: typeof authSignUpRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(authRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  PricingIndexRoute: PricingIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
