packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted
blockExoticSubdeps: false

allowBuilds:
  '@prisma/engines': true
  electron-winstaller: true
  esbuild: true
  prisma: true
  unrs-resolver: true
